### ISSUE TITLE
Implement equivalent change "(Custom) contrasts for interaction terms RM AN(C)OVA"

### ISSUE THREAD

**Issue by TimKDJ** [jasp-stats/ANOVA#3]
See https://github.com/jasp-stats/jasp-desktop/pull/4089

**Comment by JohnnyDoorn** [comment]
Yes! I am waiting for my PR to be merged/approved, when that's the case I'll PR here too

**Comment by TimKDJ** [comment]
Yeah totally. This is just a way for me to keep track of what is expected where so it's not lost
